"""Add runs, react_conversations, and run_events tables for agent platform

Revision ID: 02de7a8c7705
Revises: 4ef04bd8548b
Create Date: 2026-01-08 11:54:28.014854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02de7a8c7705'
down_revision: Union[str, Sequence[str], None] = '4ef04bd8548b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('message_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting_input', 'completed', 'failed', 'cancelled', name='run_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input_message', sa.Text(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waiting_instance_id', sa.String(length=50), nullable=True),
    sa.Column('input_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_message_id', 'runs', ['message_id'], unique=False)
    op.create_index('ix_runs_session_id', 'runs', ['session_id'], unique=False)
    op.create_index('ix_runs_status', 'runs', ['status'], unique=False)
    op.create_index('ix_runs_tenant_id', 'runs', ['tenant_id'], unique=False)
    op.create_index('ix_runs_user_id', 'runs', ['user_id'], unique=False)
    op.create_index('ix_runs_workspace_id', 'runs', ['workspace_id'], unique=False)
    op.create_table('react_conversations',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('instance_id', sa.String(length=50), nullable=True),
    sa.Column('delegation_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'observation', name='agent_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_react_conversations_instance_id', 'react_conversations', ['instance_id'], unique=False)
    op.create_index('ix_react_conversations_run_id', 'react_conversations', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('instance_id', sa.String(length=50), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_events_run_id', 'run_events', ['run_id'], unique=False)
    op.create_index('ix_run_events_sequence', 'run_events', ['run_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_events_sequence', table_name='run_events')
    op.drop_index('ix_run_events_run_id', table_name='run_events')
    op.drop_table('run_events')
    op.drop_index('ix_react_conversations_run_id', table_name='react_conversations')
    op.drop_index('ix_react_conversations_instance_id', table_name='react_conversations')
    op.drop_table('react_conversations')
    op.drop_index('ix_runs_workspace_id', table_name='runs')
    op.drop_index('ix_runs_user_id', table_name='runs')
    op.drop_index('ix_runs_tenant_id', table_name='runs')
    op.drop_index('ix_runs_status', table_name='runs')
    op.drop_index('ix_runs_session_id', table_name='runs')
    op.drop_index('ix_runs_message_id', table_name='runs')
    op.drop_table('runs')
    op.execute("DROP TYPE IF EXISTS agent_message_role")
    op.execute("DROP TYPE IF EXISTS run_status")
    # ### end Alembic commands ###