"""add_log_connectors_and_log_field_mappings_tables

Revision ID: 134971f8d2a6
Revises: b2c3d4e5f6a7
Create Date: 2026-03-17 14:01:18.724369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '134971f8d2a6'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connector_name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=50), server_default=sa.text("'elasticsearch'"), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_connectors_tenant', 'log_connectors', ['tenant_id'], unique=False)
    op.create_index('ix_log_connectors_tenant_type', 'log_connectors', ['tenant_id', 'connector_type'], unique=False)
    op.create_table('log_field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('mapping_name', sa.String(length=255), nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['log_connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_field_mappings_connector', 'log_field_mappings', ['connector_id'], unique=False)
    op.create_index('ix_log_field_mappings_connector_default', 'log_field_mappings', ['connector_id', 'is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_field_mappings_connector_default', table_name='log_field_mappings')
    op.drop_index('ix_log_field_mappings_connector', table_name='log_field_mappings')
    op.drop_table('log_field_mappings')
    op.drop_index('ix_log_connectors_tenant_type', table_name='log_connectors')
    op.drop_index('ix_log_connectors_tenant', table_name='log_connectors')
    op.drop_table('log_connectors')
    # ### end Alembic commands ###
