"""add_last_cursor_to_log_connectors_and_ingested_logs_table

Revision ID: 1aee0f12ea6d
Revises: 134971f8d2a6
Create Date: 2026-03-17 15:42:30.215688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aee0f12ea6d'
down_revision: Union[str, Sequence[str], None] = '134971f8d2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('raw_document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_mapping_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('es_index', sa.String(length=255), nullable=False),
    sa.Column('es_doc_id', sa.String(length=255), nullable=False),
    sa.Column('log_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['log_connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'es_doc_id', name='ux_ingested_logs_connector_doc')
    )
    op.create_index('ix_ingested_logs_connector_ingested', 'ingested_logs', ['connector_id', 'ingested_at'], unique=False)
    op.create_index('ix_ingested_logs_connector_timestamp', 'ingested_logs', ['connector_id', 'log_timestamp'], unique=False)
    op.add_column('log_connectors', sa.Column('last_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_connectors', 'last_cursor')
    op.drop_index('ix_ingested_logs_connector_timestamp', table_name='ingested_logs')
    op.drop_index('ix_ingested_logs_connector_ingested', table_name='ingested_logs')
    op.drop_table('ingested_logs')
    # ### end Alembic commands ###
