"""add_da_only_to_router_mode_enum

Revision ID: 2620a0e773a3
Revises: 8c6c62621633
Create Date: 2026-02-20 12:30:28.644677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2620a0e773a3'
down_revision: Union[str, Sequence[str], None] = '8c6c62621633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE router_mode ADD VALUE 'DA_ONLY'")


def downgrade() -> None:
    """Downgrade schema."""
    pass