"""Added permission_status_mirroring for file permission sync

Revision ID: 4d797520afb0
Revises: 0751e5741f00
Create Date: 2025-12-03 09:00:51.915620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d797520afb0'
down_revision: Union[str, Sequence[str], None] = '0751e5741f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('permission_mirroring_status', sa.String(length=50), server_default=sa.text("'NOT INITIATED'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'permission_mirroring_status')
    # ### end Alembic commands ###
