"""add_orchestrator_config_table

Revision ID: 4ef04bd8548b
Revises: 03a2611cda2a
Create Date: 2026-01-06 11:37:47.299928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef04bd8548b'
down_revision: Union[str, Sequence[str], None] = '03a2611cda2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrator_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('router_mode', sa.Enum('AUTO', 'SEARCH_ONLY', 'ACTION_ONLY', name='router_mode', create_type=False), server_default='AUTO', nullable=False),
    sa.Column('router_classification_prompt', sa.Text(), nullable=True),
    sa.Column('response_synthesis_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_index('ix_orchestrator_config_workspace', 'orchestrator_config', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orchestrator_config_workspace', table_name='orchestrator_config')
    op.drop_table('orchestrator_config')
    op.execute("DROP TYPE IF EXISTS router_mode")
    # ### end Alembic commands ###