"""gateway tables
Revision ID: a3235d7ece3f
Revises: dc06546c0d29
Create Date: 2025-12-23 12:39:34.194484
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3235d7ece3f'
down_revision: Union[str, Sequence[str], None] = 'dc06546c0d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_permission',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('mutex_locks',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fencing_token', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('rotation_mutex',
    sa.Column('id', sa.Boolean(), nullable=False),
    sa.Column('held_by', sa.Text(), nullable=True),
    sa.Column('held_since', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signing_keys',
    sa.Column('kid', sa.Text(), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('private_pem', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CURRENT', 'NEXT', 'RETIRED', name='key_status'), nullable=False),
    sa.Column('not_before', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('not_after', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kid')
    )
    # Step 1: Create tenant table without tenant_owner FK
    op.create_table('tenant',
                    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('org_external_id', sa.String(length=200), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'DELETED', 'PENDING_OPENFGA_SETUP', name='tenant_status'),
                  nullable=False),
        sa.Column('allowed_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('status_updated_by', sa.UUID(as_uuid=False), nullable=True),
        sa.Column('status_reason', sa.Text(), nullable=True),
        sa.Column('tenant_owner', sa.UUID(as_uuid=False), nullable=True),  # No FK constraint yet!
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('org_external_id')
    )

    # Create indexes for tenant
    op.create_index('ix_tenant_status', 'tenant', ['status'])
    op.create_index('ix_tenant_created_at', 'tenant', ['created_at'])

    # Step 2: Create user table (now tenant exists, so FK to tenant works)
    op.create_table('user',
            sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=True),
        sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED', name='user_status'),
                  nullable=False),
        sa.Column('first_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('tenant_id', 'email', name='ux_user_tenant_email')
    )

    op.create_index('ix_user_last_login_at', 'user', ['last_login_at'], unique=False)
    op.create_index('ix_user_tenant_status', 'user', ['tenant_id', 'status'], unique=False)

    op.create_foreign_key(
        'fk_tenant_owner_user',  # constraint name
        'tenant',
        'user',
        ['tenant_owner'],
        ['id'],
        ondelete='SET NULL'
    )

    op.create_table('chat',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('incognito', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_created_by', 'chat', ['tenant_id', 'created_by'], unique=False)
    op.create_index('ix_chat_tenant_incognito', 'chat', ['tenant_id', 'incognito'], unique=False)
    op.create_index('ix_chat_tenant_non_incognito', 'chat', ['tenant_id'], unique=False, postgresql_where=sa.text('incognito = false'))
    op.create_index('ix_chat_tenant_updated_at', 'chat', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.Enum('AZURE_AD', name='idp_provider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=200), nullable=False),
    sa.Column('provider_org_id', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('SSO_LOGIN', 'FILE_PERMISSIONS', name='member_source'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='ux_member_provider_user')
    )
    op.create_index('ix_member_provider_org', 'member', ['provider', 'provider_org_id'], unique=False)
    op.create_index('ix_member_source', 'member', ['source'], unique=False)
    op.create_index('ix_member_user_id', 'member', ['user_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='ux_role_tenant_key')
    )
    op.create_index('ix_role_tenant_name', 'role', ['tenant_id', 'name'], unique=False)
    op.create_table('sso_identity',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('AZURE_AD', name='idp_provider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=200), nullable=False),
    sa.Column('provider_org_id', sa.String(length=200), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='ux_sso_identity_provider_user')
    )
    op.create_index('ix_sso_identity_provider_org', 'sso_identity', ['provider', 'provider_org_id'], unique=False)
    op.create_index('ix_sso_identity_user_id', 'sso_identity', ['user_id'], unique=False)
    op.create_table('tenant_authz_store',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_identity',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Enum('AZURE_AD', name='idp_provider'), nullable=False),
    sa.Column('provider_org_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_org_id', name='ux_tenant_identity_provider_org')
    )
    op.create_table('user_invitation',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('inviter', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_invitation_expires_at', 'user_invitation', ['expires_at'], unique=False)
    op.create_index('ix_user_invitation_tenant_email', 'user_invitation', ['tenant_id', 'email'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chat_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_chat_created_at', 'message', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_message_tenant_chat', 'message', ['tenant_id', 'chat_id'], unique=False)
    op.create_index('ix_message_user_id', 'message', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop indexes and tables in reverse order
    op.drop_index('ix_message_user_id', table_name='message')
    op.drop_index('ix_message_tenant_chat', table_name='message')
    op.drop_index('ix_message_chat_created_at', table_name='message')
    op.drop_table('message')

    op.drop_index('ix_user_invitation_tenant_email', table_name='user_invitation')
    op.drop_index('ix_user_invitation_expires_at', table_name='user_invitation')
    op.drop_table('user_invitation')

    op.drop_table('tenant_identity')
    op.drop_table('tenant_authz_store')

    op.drop_index('ix_sso_identity_user_id', table_name='sso_identity')
    op.drop_index('ix_sso_identity_provider_org', table_name='sso_identity')
    op.drop_table('sso_identity')

    op.drop_index('ix_role_tenant_name', table_name='role')
    op.drop_table('role')

    op.drop_index('ix_member_user_id', table_name='member')
    op.drop_index('ix_member_source', table_name='member')
    op.drop_index('ix_member_provider_org', table_name='member')
    op.drop_table('member')

    op.drop_index('ix_chat_tenant_updated_at', table_name='chat')
    op.drop_index('ix_chat_tenant_non_incognito', table_name='chat', postgresql_where=sa.text('incognito = false'))
    op.drop_index('ix_chat_tenant_incognito', table_name='chat')
    op.drop_index('ix_chat_created_by', table_name='chat')
    op.drop_table('chat')

    # **ADD THIS: Drop the FK constraint from tenant to user FIRST**
    op.drop_constraint('fk_tenant_owner_user', 'tenant', type_='foreignkey')

    # Now drop user table (FK constraint is gone)
    op.drop_index('ix_user_tenant_status', table_name='user')
    op.drop_index('ix_user_last_login_at', table_name='user')
    op.drop_table('user')

    # Now drop tenant table
    op.drop_index('ix_tenant_status', table_name='tenant')
    op.drop_index('ix_tenant_created_at', table_name='tenant')
    op.drop_table('tenant')

    # Drop other tables
    op.drop_table('signing_keys')
    op.drop_table('rotation_mutex')
    op.drop_table('mutex_locks')
    op.drop_table('app_permission')

    op.execute('DROP TYPE IF EXISTS key_status CASCADE')
    op.execute('DROP TYPE IF EXISTS tenant_status CASCADE')
    op.execute('DROP TYPE IF EXISTS user_status CASCADE')
    op.execute('DROP TYPE IF EXISTS idp_provider CASCADE')
    op.execute('DROP TYPE IF EXISTS member_source CASCADE')
    op.execute('DROP TYPE IF EXISTS message_role CASCADE')