"""add external file info column

Revision ID: a94fd320e0ec
Revises: 4d797520afb0
Create Date: 2025-12-04 16:55:41.279308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a94fd320e0ec'
down_revision: Union[str, Sequence[str], None] = '4d797520afb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('external_file_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Stores file_id and drive_id of external sources, e.g., SharePoint'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'external_file_info')
    # ### end Alembic commands ###
