"""Added is_deleted flag to ingestion_jobs table

Revision ID: dc06546c0d29
Revises: a94fd320e0ec
Create Date: 2025-12-09 13:22:33.053690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc06546c0d29'
down_revision: Union[str, Sequence[str], None] = 'a94fd320e0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'is_deleted')
    # ### end Alembic commands ###
