"""add workspace_id to connections table

Revision ID: e9aa925e4d2f
Revises: 1bc4c81d7345
Create Date: 2025-12-30 11:12:21.009970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aa925e4d2f'
down_revision: Union[str, Sequence[str], None] = '1bc4c81d7345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index('ix_connection_workspace', 'connections', ['workspace_id'], unique=False)
    op.create_unique_constraint('ux_connection_workspace_connector_type', 'connections', ['workspace_id', 'connector_type_id'])
    op.create_foreign_key(None, 'connections', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_constraint('ux_connection_workspace_connector_type', 'connections', type_='unique')
    op.drop_index('ix_connection_workspace', table_name='connections')
    op.drop_column('connections', 'workspace_id')
    # ### end Alembic commands ###
